Project "e-ethelodria" {
  database_type: 'MySQL'
  Note: '''
    # e-ethelodria
    ## A Crowd Sourcing Humanitarian Aid Web App.
  '''
}

Table User [headercolor: #24BAB1]
{
  id binary(16) [pk, default: `UUID_TO_BIN(UUID())`]
  username varchar [unique]
  password varchar
  email varchar
  telephone varchar(15)
  name varchar
  surname varchar
  longitude float
  latitude float
  is_admin boolean [default: false]
  is_diasostis boolean [default: false]
  is_citizen boolean [default: false]
  note: 'The table where user information and their role is stored.'
}

Table Base  [headercolor: #EB801B]
{
  id binary(16) [pk, default: `UUID_TO_BIN(UUID())`]
  admin binary(16) [ref: - User.id]
  longitude float
  latitude float 
}

Table Announcement_List
{
  id binary(16) [ref: > Base.id]
  announcement binary(16) [ref: - Announcement.id]
}

Table Product_List
{
  id binary(16) [ref: > Base.id, ref: > Task.id, ref: > Vehicle.id, ref: > Announcement.id]
  product integer [ref: > Product.id]
  quantity integer

}

Table Task_List
{
  id binary(16) [ref: > User.id, ref: > Vehicle.id] 
  task binary(16) [ref: - Task.id]
}

Table Product [headercolor: #79AD51]
{
  id integer [pk, increment]
  name varchar
  category integer [ref: - Category.id]

}

Table Details [headercolor: #99CD71]
{
  product integer [ref: > Product.id]
  name varchar
  value varchar
}

Table Category [headercolor: #2D6512]
{
  id integer [pk]
  name varchar   
}

Table Vehicle  [headercolor: #4B82B0]
{
  id binary(16) [pk, default: `UUID_TO_BIN(UUID())`]
  owner binary(16) [ref: - User.id]
  longitude float
  latitude float
  state vehicle_state
}

Table Task  [headercolor: #CA4242]
{
  id binary(16) [pk, default: `UUID_TO_BIN(UUID())`]
  user_id binary(16) [ref: > User.id]
  date_in date
  accepted_in date
  date_out date
  state task_state
  type task_type
}

enum vehicle_state {
  loading
  free 
  offloading
}

enum task_state {
  published 
  pending 
  done
}

enum task_type {
  request
  offering
}

Table Announcement [headercolor: #E4A62E]
{
  id binary(16) [pk, default: `UUID_TO_BIN(UUID())`]
  published_in date
  text varchar
}
