
Enum "users_role_enum" {
  "ADMIN"
  "RESCUER"
  "CITIZEN"
}

Enum "request_status_enum" {
  "PENDING"
  "ASSUMED"
  "COMPLETED"
}

Enum "offer_status_enum" {
  "PENDING"
  "ASSUMED"
  "COMPLETED"
}

Enum "rescue_vehicle_type_enum" {
  "PERSONAL USE"
  "VAN"
  "PICKUP TRUCK"
}

Enum "rescue_vehicle_status_enum" {
  "WAITING"
  "ACTIVE"
  "UNAVAILABLE"
}

Table "location" {
  "id" BINARY(16) [pk, default: `UUID_TO_BIN(UUID())`]
  "latitude" DOUBLE
  "longitude" DOUBLE
  "distance_to_base" DOUBLE
}

Table "users" {
  "id" BINARY(16) [pk, default: `UUID_TO_BIN(UUID())`]
  "username" VARCHAR(255) [not null]
  "password" VARCHAR(255) [not null]
  "role" users_role_enum [not null]
  "full_name" VARCHAR(255)
  "email" VARCHAR(255) [not null]
  "phone" VARCHAR(20) [not null]
  "location_id" BINARY(16)
}

Table "product_category" {
  "id" BINARY(16) [pk, default: `UUID_TO_BIN(UUID())`]
  "name" VARCHAR(255) [unique, not null]
}

Table "product" {
  "id" BINARY(16) [pk, default: `UUID_TO_BIN(UUID())`]
  "name" VARCHAR(255) [not null]
  "description" TEXT
  "quantity" INT [not null, default: 0]
  "offer_quantity" INT [not null, default: 2]
  "category_id" BINARY(16) [not null]
}

Table "product_details" {
  "id" BINARY(16) [pk, default: `UUID_TO_BIN(UUID())`]
  "name" VARCHAR(255) [not null]
  "value" VARCHAR(255) [not null]
  "product_id" BINARY(16)
}

Table "request" {
  "id" BINARY(16) [pk, default: `UUID_TO_BIN(UUID())`]
  "citizen_id" BINARY(16)
  "rescuer_id" BINARY(16)
  "product_id" BINARY(16)
  "number_of_people" INT [not null]
  "quantity" INT
  "status" request_status_enum [default: "PENDING"]
  "created_at" DATETIME [default: `CURRENT_TIMESTAMP`]
  "assumed_at" DATETIME
  "completed_at" DATETIME
}

Table "announcement" {
  "id" BINARY(16) [pk, default: `UUID_TO_BIN(UUID())`]
  "name" VARCHAR(255) [not null]
  "description" TEXT
  "announcement_date" DATETIME [default: `CURRENT_TIMESTAMP`]
}

Table "announcements_needs" {
  "id" BINARY(16) [pk, default: `UUID_TO_BIN(UUID())`]
  "announcement_id" BINARY(16) [not null]
  "product_id" BINARY(16) [not null]
}

Table "offer" {
  "id" BINARY(16) [pk, default: `UUID_TO_BIN(UUID())`]
  "citizen_id" BINARY(16)
  "rescuer_id" BINARY(16)
  "product_id" BINARY(16)
  "announcement_id" BINARY(16)
  "quantity" INT
  "status" offer_status_enum [default: "PENDING"]
  "created_at" DATETIME [default: `CURRENT_TIMESTAMP`]
  "assumed_at" DATETIME
  "completed_at" DATETIME
}

Table "rescue_vehicle" {
  "id" BINARY(16) [pk, default: `UUID_TO_BIN(UUID())`]
  "type" rescue_vehicle_type_enum [not null]
  "status" rescue_vehicle_status_enum [default: "WAITING"]
  "active_tasks" INT [default: 0]
  "rescuer_id" BINARY(16)
}

Table "rescuer_inventory" {
  "id" BINARY(16) [pk, default: `UUID_TO_BIN(UUID())`]
  "rescuer_id" BINARY(16) [not null]
  "product_id" BINARY(16) [not null]
  "amount" INT [default: 0]

  Indexes {
    (rescuer_id, product_id) [unique, name: "idx_rescuer_product"]
  }
}

Ref:"location"."id" < "users"."location_id"

Ref:"product_category"."id" < "product"."category_id"

Ref:"product"."id" < "product_details"."product_id"

Ref:"users"."id" < "request"."citizen_id"

Ref:"product"."id" < "request"."product_id"

Ref:"users"."id" < "request"."rescuer_id"

Ref:"announcement"."id" < "announcements_needs"."announcement_id"

Ref:"product"."id" < "announcements_needs"."product_id"

Ref:"users"."id" < "offer"."citizen_id"

Ref:"product"."id" < "offer"."product_id"

Ref:"users"."id" < "offer"."rescuer_id"

Ref:"announcement"."id" < "offer"."announcement_id"

Ref:"users"."id" < "rescue_vehicle"."rescuer_id"

Ref:"users"."id" < "rescuer_inventory"."rescuer_id"

Ref:"product"."id" < "rescuer_inventory"."product_id"
